import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.jsx'],
  theme: {
    extend: {
      colors: {
        'deep-navy': '#000825',
        'teal-medical': '#00A4A6',
        'gold-accent': '#D4AF37',
        'mint-surface': '#D9F2E2',
        'pure-white': '#FFFFFF',
        'danger-red': '#E63946',
        background: '#07122e',
        surface: '#07122e',
        'surface-container-lowest': '#020c29',
        'surface-container-low': '#0f1a37',
        'surface-container': '#141e3b',
        'surface-container-high': '#1f2946',
        'surface-container-highest': '#2a3452',
        'on-surface': '#dbe1ff',
        'on-surface-variant': '#bcc9c9',
        primary: '#5cd8da',
        'on-primary': '#003738',
        'primary-container': '#00a4a6',
        'primary-fixed-dim': '#5cd8da',
        secondary: '#e9c349',
        'on-secondary': '#3c2f00',
        'secondary-container': '#af8d11',
      },
      fontFamily: {
        'headline-xl': ['Montserrat', 'sans-serif'],
        'headline-lg': ['Montserrat', 'sans-serif'],
        'headline-lg-mobile': ['Montserrat', 'sans-serif'],
        'title-md': ['Montserrat', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'quiz-option': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['3.6rem', { lineHeight: '4.4rem', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['2.8rem', { lineHeight: '3.4rem', fontWeight: '600' }],
        'headline-lg-mobile': ['2.4rem', { lineHeight: '3.0rem', fontWeight: '600' }],
        'title-md': ['2.0rem', { lineHeight: '2.8rem', fontWeight: '600' }],
        'body-lg': ['1.8rem', { lineHeight: '2.8rem', fontWeight: '400' }],
        'body-md': ['1.6rem', { lineHeight: '2.4rem', fontWeight: '400' }],
        'label-caps': ['1.2rem', { lineHeight: '1.6rem', letterSpacing: '0.1em', fontWeight: '700' }],
        'quiz-option': ['1.7rem', { lineHeight: '2.2rem', fontWeight: '500' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base: '0.4rem',
        xs: '0.8rem',
        sm: '1.2rem',
        gutter: '1.6rem',
        md: '2.4rem',
        'container-margin': '2.0rem',
        lg: '4.0rem',
        xl: '6.4rem',
      },
    },
  },
  plugins: [forms],
};
